import numpy as np, pandas as pd, os, math, random, time
import rdkit
from rdkit import Chem
from rdkit.Chem import Descriptors, Draw, QED


import torch
from torch.utils.data import TensorDataset, DataLoader
from torch.utils.data import random_split
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

def define_vocabulary():
    
    vocab = [
    # Special tokens [padding, start, end, unknown symbol]
    "<PAD>", "<START>", "<END>", "<UNK>",
    # Common atoms
    "C", "O", "N", "S", "P", "F", "Cl", "Br", "I",
    # Aromatic atoms (lowercase form often used in SMILES)
    "c", "o", "n", "s", "p",
    # Bonds
    "-", "=", "#",
    # Branching / rings
    "(", ")", "[", "]",
    # Ring closure digits
    "1","2","3","4","5","6","7","8","9",
    # Stereo / charges
    "@", "@@", "+", "H"
     ]

    # Build dictionaries: use increasing integer numbers for tokenization
    stoi = {tok: i for i, tok in enumerate(vocab)}   # from tokens to integers
    itos = {i: tok for tok, i in stoi.items()}     # from integers to tokens

    return vocab, stoi, itos

    

def define_tokens(smiles: str):
    
    """ Takes in a SMILES string and returns the tokenization = split string into tokens """
    
    tokens = []
    i = 0
    while i < len(smiles):
        # check two-character tokens
        if smiles[i:i+2] in ("Cl", "Br", "@@"):
            tokens.append(smiles[i:i+2])
            i += 2
        else:
            tokens.append(smiles[i])
            i += 1
    return tokens

def encode(smiles):
    
    """ Tokenization: from tokens to sequence of integers """
    
    tokens = ["<START>"] + define_tokens(smiles) + ["<END>"]
    unk_id = stoi["<UNK>"]
    return [stoi.get(t, unk_id) for t in tokens]

def decode(id_list):
    
    """ De-tokenization: from sequence of integers to tokens """   
    
    tokens = [itos[i] for i in id_list if itos[i] not in ("<PAD>", "<START>", "<END>")]
    return "".join(tokens)

def run_epoch_rnn(loader, train=True, clip=1.0):
    model.train(train)
    total_loss, total_tokens = 0.0, 0
    
    for xb, yb in loader:
        xb, yb = xb.to(device), yb.to(device)
        if train:
            optimizer.zero_grad()
        pred = model(xb)                            # (B,T,V)
        labels = yb.reshape(-1)
        
                         # predictions from the NN        # actual target from the data to compare against
        loss = loss_fn(pred.reshape(-1, V), labels)
        if train:
            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), clip)
            optimizer.step()
            
        # count non-PAD targets for averaging
        ntok = (yb != pad_id).sum().item()
        total_loss += loss.item() * max(ntok, 1)
        total_tokens += max(ntok, 1)
    return total_loss / total_tokens      # this ensures fair averaging per token, regarless of seqeucne length.
                                          # wthout this, the reported loss would be biased toward short or long SMILES


@torch.no_grad()
def sample_one_SMILE(max_len=120, temperature=temp, top_k=30):     # 120 is the pad length

    """
    Generate a single SMILES string from the trained RNN model.

    Starting with a <START> token, the model repeatedly predicts the probability
    distribution of the next token conditioned on all tokens generated so far.
    At each step:
      1. The prefix (list of token IDs generated so far) is passed through the model to obtain logits for the last position.
      2. Logits are scaled by `temperature` to control distribution sharpness
         (T < 1.0 → sharper/more greedy, T > 1.0 → flatter/more random).
      3. If `top_k` is set, restricts sampling to the top-k most probable tokens (optional)
      4. A token ID is sampled from the resulting categorical distribution and appended.

    The loop terminates when either:
      - The <END> token is generated, or
      - The sequence reaches `max_len` tokens.

    This approach is known as autoregressive sampling
    
    Args:
        max_len (int): Maximum number of tokens to generate before stopping.
        temperature (float): Sampling temperature; controls randomness of token selection.
        top_k (int or None): If set, sample only from the top-k most probable tokens.

    Returns:
        str: A SMILES string generated by the model (without <START>/<END>/<PAD> tokens).
    """
    
    model.eval()
    ids = [stoi["<START>"]]    # begin list with <START>
    for _ in range(max_len):

        # define the prefix (= tokenized string generated so far)
        x = torch.tensor(ids, dtype=torch.long, device=device).unsqueeze(0)  # (1,t)

        # extract network output at the last step
        logits = model(x)[:, -1, :]  # last step, shape (1t)   # this s the learned distribution before softmax
        logits = logits / max(1e-6, temperature)    # scale logits by a termperature to control sampling

        # Top-k filtering
        if top_k is not None:
            k = min(top_k, V)
            vals, idxs = torch.topk(logits, k=k, dim=-1)     # restrict to the top-k most likely tokens
            probs = F.softmax(vals, dim=-1)    # probabilities that sum to 1
            next_id = idxs[0, torch.multinomial(probs, 1)].item()
        else:
            probs = F.softmax(logits, dim=-1)       # build the distribution
            next_id = torch.multinomial(probs, 1).item()       # sample from the distribution

        ids.append(next_id)
        if next_id == stoi["<END>"]:     # if <END>, stop; otherwise, feed the updates `ids` back into the GRU for the next step
            break

    return decode(ids)
    